### ISSUE TITLE
Suggestion: Add more targets to hook

### ISSUE THREAD

**Issue by bkmo** [adonespitogo/node-snapback#2]
Here is an example of a hook I run that tarkets more kernels:  (sorry but code blocks mess it up)
`[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
Operation = Remove
Target = systemd
Target = linux
Target = linux-lts

[Trigger]
Type = File
Operation = Install
Operation = Upgrade
Target = boot/vmlinuz-linux
Target = boot/vmlinuz-linux-lts
Target = usr/lib/initcpio/*

[Action]
Description = Backup boot partition (pre)...
When = PreTransaction
Exec = /usr/share/libalpm/scripts/backup-boot-partition pre
AbortOnFail`

**Comment by adonespitogo** [comment]
Hi, thanks for the suggestion. Can you please help me with this? This is just a simple change in [this file](https://github.com/adonespitogo/node-snapback/blob/main/files/95-bootbackup.hook) then create a PR afterwards. I'm quite busy with my hyprland setup right now :)

**Comment by bkmo** [comment]
When I get a chance I will clone your repo and have a look.

**Comment by adonespitogo** [comment]
This is now added in `v1.1.2`. Thanks @bkmo
